import { useState, useEffect } from "react";
import { useLang, useT } from "./i18n.jsx";

function Logo({ size = 32 }) {
  return (
    <svg width={size} height={size} viewBox="0 0 32 32" fill="none">
      <defs><linearGradient id="blg" x1="0" y1="0" x2="32" y2="32" gradientUnits="userSpaceOnUse"><stop stopColor="#1a82ff"/><stop offset="1" stopColor="#5b4fff"/></linearGradient></defs>
      <rect width="32" height="32" rx="9" fill="url(#blg)"/>
      <rect x="4" y="4" width="11" height="11" rx="3" fill="white" opacity=".95"/>
      <rect x="17" y="4" width="11" height="11" rx="3" fill="white" opacity=".6"/>
      <rect x="4" y="17" width="11" height="11" rx="3" fill="white" opacity=".6"/>
      <rect x="17" y="17" width="11" height="11" rx="3" fill="white" opacity=".95"/>
      <rect x="13" y="13" width="6" height="6" rx="1.5" fill="white" opacity=".28"/>
    </svg>
  );
}

const POSTS = [
  // ENGLISH
  {slug:"personalised-demos-reply-rate",lang:"en",title:"How Personalised Sales Demos Increase Reply Rates by 3x",excerpt:"Visual personalisation outperforms text-only cold outreach in every study. Here is the data and how to do it at scale.",cat:"Strategy",rt:"5 min",date:"Mar 2025",tags:["personalisation","cold email","reply rate"],body:"Personalised outreach is not new. What is new is doing it visually and at scale. When a prospect opens an email and sees their own company logo placed perfectly on your product screenshot, something clicks. It signals effort. It signals relevance. And it converts.\n\nStudies consistently show that visual personalisation outperforms text-only approaches. Reply rates of 15 to 30% are achievable for teams that implement logo-based demo personalisation versus the industry average of 2 to 5% for generic cold email.\n\nThe core mechanic is simple: upload your product screenshot once, auto-fetch your prospect's logo, and send a tailored image that looks like you spent an hour on it. You spent 20 seconds.\n\nThis is not about manipulation. It is about showing your prospect that you understand their world. A logo is the most recognisable visual asset a company has. When yours appears on someone's tool in context, it creates immediate rapport.\n\nScale is the key advantage. Doing this manually in Figma for one prospect might take 30 minutes. Doing it for 50 prospects with Logoplacers takes 8 minutes total."},
  {slug:"cold-email-personalisation-sdrs",lang:"en",title:"Cold Email Personalisation at Scale: A Practical Guide for SDRs",excerpt:"Most SDRs spend 70% of their time on manual research. Here is how to cut that to under 5% without sacrificing quality.",cat:"Playbook",rt:"7 min",date:"Mar 2025",tags:["SDR","cold email","automation"],body:"The average SDR spends 3.5 hours per day on research and personalisation. That is time not spent on calls, not spent closing. And most of that personalisation is basic: first name, company name, maybe a LinkedIn detail. Prospects see through it immediately.\n\nThe shift to visual personalisation changes the economics. Instead of writing a unique opening line for every prospect, you create one great visual asset and let automation do the personalisation layer.\n\nHere is the workflow: build your demo screenshot in Logoplacers once. Add text layers with placeholders like name and company. Then paste your prospect list and let the tool generate 50 unique personalised images in under 2 minutes.\n\nEach image gets sent directly from your Gmail with a 15 to 30 second anti-spam delay between sends. The prospect receives an email that looks like you hand-crafted a custom demo specifically for them.\n\nThe SDRs who adopt this report 4 to 6x increases in positive reply rates within the first two weeks."},
  {slug:"visual-demos-b2b-outreach",lang:"en",title:"Why Visual Demos Work Better Than Text in B2B Outreach",excerpt:"The human brain processes images 60,000x faster than text. Here is why that matters for your sales pipeline.",cat:"Strategy",rt:"4 min",date:"Feb 2025",tags:["visual demos","B2B","sales"],body:"The brain processes visual information 60,000 times faster than text. In cold outreach, you have approximately 3 seconds to capture attention before your email is archived. A personalised visual demo is your strongest tool for those 3 seconds.\n\nText-only cold emails rely on the prospect reading far enough to understand your value proposition. Most do not. A well-designed visual demo communicates the core value instantly before a single word is read.\n\nThe psychology is straightforward. When a B2B buyer sees their company logo placed on a product screenshot, several things happen simultaneously. They recognise their brand and get immediate attention. They see it in context with your tool and get instant product comprehension. They feel that this email was prepared specifically for them.\n\nNone of this requires expensive video production. A single high-quality screenshot with a well-placed logo achieves the same psychological effect at 1% of the cost and time."},
  {slug:"gmail-bulk-send-personalised",lang:"en",title:"How to Send 100 Personalised Emails from Gmail in Under 10 Minutes",excerpt:"A step-by-step workflow for bulk personalised outreach from Gmail without getting flagged as spam.",cat:"Tutorial",rt:"6 min",date:"Feb 2025",tags:["Gmail","bulk send","tutorial"],body:"Sending personalised bulk email from Gmail requires three things: unique content per recipient, natural send timing, and a good sender reputation.\n\nLogoplacers handles the first two automatically. Each recipient gets a genuinely unique personalised image attached. Sends are spaced 15 to 30 seconds apart to mimic natural human sending behaviour.\n\nThe workflow: upload your screenshot, arrange logo placement and text layers, paste your prospect list, write your email with name and company placeholders, connect Gmail via OAuth, and hit send.\n\nImportant note on warm sending: new Gmail accounts should ramp up slowly. Start with 20 to 30 sends per day for the first two weeks before scaling. Use a custom domain rather than a personal Gmail address for B2B outreach. A Google Workspace account is significantly better than personal Gmail for deliverability."},
  {slug:"logo-personalisation-saas-sales",lang:"en",title:"Logo Personalisation: The Easiest Win in SaaS Sales Outreach",excerpt:"One change to your outreach strategy that takes 20 minutes to implement and immediately improves every metric.",cat:"Strategy",rt:"4 min",date:"Feb 2025",tags:["SaaS","logo","personalisation"],body:"If you work in SaaS sales, you are competing against dozens of other tools for the same buyer's attention. Your product might be genuinely better. But your outreach looks exactly like everyone else's.\n\nLogo personalisation is the lowest-effort, highest-impact change you can make right now. It takes one afternoon to set up and immediately differentiates every email you send.\n\nHere is the simple version: take a screenshot of your product with a company's logo already placed on it. Send that as part of your cold email. The prospect sees their brand in your UI. Conversion begins.\n\nThe more scalable version: use Logoplacers to automate this for your entire prospect list. One upload, 100 personalised demos, all sent from Gmail. The conversion lift pays for the tool in the first week."},
  {slug:"write-cold-email-that-gets-replies",lang:"en",title:"How to Write a Cold Email That Actually Gets Replies in 2025",excerpt:"The anatomy of a high-converting cold email: subject line, opening, value prop, CTA. With real examples.",cat:"Playbook",rt:"8 min",date:"Mar 2025",tags:["cold email","copywriting","reply rate"],body:"Most cold emails fail for one of three reasons: they are too long, too generic, or they ask for too much too soon.\n\nHere is the anatomy of a cold email that consistently gets replies.\n\nSubject line: 3 to 6 words. Specific beats clever. 'Question about your sales process' outperforms 'Revolutionise your pipeline with AI'. The goal is a curious open, not a click-bait promise.\n\nOpening line: Never start with 'I'. Start with them. 'Noticed you recently launched X' or 'Your team is scaling fast in Y' shows research and earns attention.\n\nValue proposition: One sentence. What do you do and why does it matter to this specific person? Not a feature list. A single concrete outcome.\n\nVisual hook: Include a personalised demo image. A screenshot with their logo placed on it communicates more than three paragraphs of copy. It is the fastest way to make the abstract concrete.\n\nCall to action: Ask for something tiny. 'Worth a 15-minute call?' or 'Would this be useful for your team?' A yes/no question converts better than 'Book a demo on my Calendly'.\n\nLength: Under 100 words for the text. The image does the heavy lifting."},
  {slug:"sales-email-templates-b2b",lang:"en",title:"5 Sales Email Templates That Generate Meetings (Copy-Paste)",excerpt:"Battle-tested cold email templates for SaaS, agencies, and B2B services. Personalise and send today.",cat:"Playbook",rt:"6 min",date:"Mar 2025",tags:["templates","cold email","B2B"],body:"Here are five cold email templates with above-average reply rates. Use them as starting points and personalise the details.\n\nTemplate 1 — The Visual Hook\nSubject: [Company] on [Your Tool]\nBody: Hi [Name], built a quick mockup of what [Company]'s logo would look like inside [Your Product]. [Attach personalised image.] Happy to show you the live version — worth 15 minutes?\n\nTemplate 2 — The Trigger\nSubject: Congrats on the funding\nBody: Hi [Name], saw [Company] just closed [round]. Teams at that stage usually hit the same bottleneck: [specific problem you solve]. We fixed this for [similar company]. Quick call this week?\n\nTemplate 3 — The Comparison\nSubject: How [Competitor Customer] handled this\nBody: Hi [Name], [Similar company] was dealing with [problem] before switching. Now they [result]. Would the same apply to [Company]?\n\nTemplate 4 — The Direct Ask\nSubject: [Problem] at [Company]?\nBody: Hi [Name], do you still handle [specific task] manually at [Company]? We built something that cuts that to minutes. One slide that explains it — want me to send it over?\n\nTemplate 5 — The Referral\nSubject: [Mutual contact] suggested I reach out\nBody: Hi [Name], [Name] mentioned you're the right person to speak with about [topic]. We help [type of company] with [outcome]. Would a quick intro call make sense?"},
  {slug:"best-sales-tool-2025",lang:"en",title:"The Best Sales Tools in 2025: What Actually Works",excerpt:"A practical guide to the sales stack that high-performing teams are using right now, and what is overhyped.",cat:"Industry",rt:"7 min",date:"Mar 2025",tags:["sales tools","2025","stack"],body:"The modern sales stack has exploded. There are hundreds of tools promising to 10x your pipeline. Most of them do not work as advertised. Here is what actually moves the needle.\n\nProspecting: Sales Navigator and Apollo are the standards. Clay is becoming popular for data enrichment at scale. The key is list quality over list size.\n\nPersonalisation: This is where most teams underinvest. Generic AI-written emails are immediately detectable. Visual personalisation — embedding the prospect's brand into a demo image — is both harder to automate generically and more effective.\n\nSequencing: Outreach and Salesloft for enterprise. Reply.io and Lemlist for SMB. The tool matters less than the sequence design.\n\nCRM: Salesforce for enterprise, HubSpot for growth stage, Pipedrive for simplicity. The best CRM is the one your team actually updates.\n\nMeetings: Calendly is the default. Chili Piper for routing complex teams.\n\nThe one underused tactic in 2025: visual demo personalisation. Teams that add a personalised screenshot to the first touchpoint consistently see 2 to 4x lift in positive replies across all other tools in their stack."},
  {slug:"how-to-use-logoplacers",lang:"en",title:"How to Use Logoplacers: Complete Guide from Setup to First Send",excerpt:"Step-by-step walkthrough of Logoplacers — from uploading your first screenshot to sending personalised demos at scale.",cat:"Tutorial",rt:"8 min",date:"Feb 2025",tags:["tutorial","getting started","guide"],body:"This guide walks you through the complete Logoplacers workflow from your first login to sending personalised demos to 50 prospects.\n\nStep 1 — Upload your base image\nThis is the screenshot you want to personalise. Ideally your product UI or a compelling visual that represents your value proposition. Drag it into the upload zone or click to browse. HEIC from iPhone is supported and converts automatically.\n\nStep 2 — Position the logo placeholder\nThe logo placeholder shows where each prospect's logo will appear. Drag it to a natural position on your image — inside a dashboard, on a header, or anywhere that looks intentional rather than pasted.\n\nStep 3 — Add text layers\nText layers let you add personalised text like the prospect's name or company. Use the sidebar to add layers and drag them to position.\n\nStep 4 — Add prospects\nPaste a list of companies in the text area on the right. Logoplacers guesses the domain and fetches the logo automatically. You can also add name, company, and email separated by commas for full personalisation.\n\nStep 5 — Preview\nClick Preview to cycle through your prospects and see exactly what each personalised image looks like before sending.\n\nStep 6 — Send or download\nConnect Gmail with one click. Write your email template using {name} and {company} placeholders. Hit send. Emails go out with natural delays to protect your deliverability. Or download a ZIP of all images to use in your own email tool."},
  {slug:"increase-reply-rates-cold-outreach",lang:"en",title:"How to Get Higher Reply Rates on Cold Outreach (Proven Tactics)",excerpt:"Every tactic that has a measurable impact on cold email reply rates, ranked from highest to lowest impact.",cat:"Strategy",rt:"7 min",date:"Jan 2025",tags:["reply rate","cold outreach","tactics"],body:"Getting higher reply rates on cold outreach is not about finding a magic phrase. It is about stacking marginal gains across every element of your outreach.\n\nHighest impact: Relevance. Reaching the right person at the right time with the right message. Signal-based outreach — targeting people who have just changed jobs, raised funding, or launched a product — outperforms list-based spray-and-pray by 5 to 10x.\n\nHigh impact: Visual personalisation. Attaching a personalised demo image with the prospect's logo increases reply rates more than any copy optimisation. The image communicates relevance faster than words.\n\nMedium impact: Subject line. Under 50 characters. Specific and curious beats clever and hypey. Test multiple versions.\n\nMedium impact: Send time. Tuesday to Thursday morning in the prospect's timezone. Avoid Monday morning and Friday afternoon.\n\nLower impact but still meaningful: Follow-up sequence. One follow-up adds 20 to 30% more replies. More than three follow-ups shows diminishing returns and risks deliverability.\n\nLowest impact that people overinvest in: The exact wording of the body copy. Once you have the right targeting and visual hook, the body copy matters much less than most people think."},
  {slug:"what-is-logoplacers",lang:"en",title:"What Is Logoplacers? The Personalised Demo Tool Explained",excerpt:"A complete overview of how Logoplacers works, who it is for, and why sales teams are switching from Figma and Loom.",cat:"Product",rt:"5 min",date:"Jan 2025",tags:["product","overview","getting started"],body:"Logoplacers is a browser-based tool that lets sales teams create personalised product demos at scale. You upload one product screenshot, and the tool generates unique versions for every prospect on your list, each with their own company logo automatically placed.\n\nThe core workflow has three steps. First, upload your screenshot and use the drag-and-drop editor to position where logos and text should appear. Second, paste your prospect list. Logoplacers automatically fetches each company's logo. Third, connect Gmail and send.\n\nWhat makes Logoplacers different: Loom requires recording per prospect. Figma requires design skills and manual work per person. Logoplacers does in 8 minutes what Figma takes 3 hours.\n\nIt is designed specifically for SDRs, AEs, and sales managers who send outreach at volume but want each touchpoint to feel personal."},
  {slug:"figma-alternative-sales-demos",lang:"en",title:"The Best Figma Alternative for Sales Demo Personalisation",excerpt:"Figma is powerful but it was not built for sales. Here is a faster workflow that requires zero design skills.",cat:"Comparison",rt:"5 min",date:"Jan 2025",tags:["Figma","alternative","comparison"],body:"Figma is an excellent design tool. It was built for product designers who need pixel-perfect control. It was not built for account executives who need to personalise 50 demo images before their 9am stand-up.\n\nThe problems with using Figma for sales demo personalisation are well-known. It requires a design background. Each personalisation is a manual process of copying a file, replacing a logo, and exporting. There is no bulk workflow. It does not connect to your email client.\n\nLogoplacers was built specifically to solve these problems. No design skills needed. Bulk personalisation is the core feature. Gmail integration means you go from personalised image to sent email without leaving the tool.\n\nThe typical switch reduces time per personalised demo from 25 to 40 minutes to under 30 seconds. For a team sending 50 demos per week, that is 20 or more hours saved every single week."},
  {slug:"seo-for-saas-sales-tools",lang:"en",title:"SEO for SaaS Sales Tools: How to Get Organic Leads in 2025",excerpt:"The SEO playbook for sales tools: which keywords convert, how to build authority, and what to publish first.",cat:"Strategy",rt:"6 min",date:"Dec 2024",tags:["SEO","SaaS","inbound"],body:"Organic search is the most scalable lead channel for SaaS tools. Here is the SEO strategy that works for sales tools specifically.\n\nKeywords that convert: Problem-aware searches ('how to personalise cold email at scale', 'figma alternative for sales') convert better than awareness-stage searches. Start with these.\n\nComparison pages: 'Logoplacers vs Lemlist', 'best alternative to Vidyard for cold email' — these capture high-intent searchers already evaluating tools.\n\nTutorial content: 'How to send 100 personalised emails from Gmail' attracts exactly the people who need your tool. Tutorial searchers have the highest trial conversion rates.\n\nBuild domain authority: Guest posts on sales blogs, being listed in tool directories like Product Hunt, G2, Capterra, and industry newsletters.\n\nTechnical fundamentals: Fast load times, proper schema markup for blog posts, canonical URLs, and a clean sitemap submitted to Google Search Console.\n\nThe compounding effect: SEO takes 6 to 12 months to show results. Start now. Publish two to three high-quality posts per month. By the time you are ready to scale paid acquisition, organic will already be generating leads."},

  // SWEDISH
  {slug:"personaliserade-demos-svarsprocent",lang:"sv",title:"Hur personaliserade säljdemos ökar svarsfrekvensen med 3x",excerpt:"Visuell personalisering slår textbaserad kall outreach i alla studier. Här är datan och hur du gör det i skala.",cat:"Strategi",rt:"5 min",date:"Mar 2025",tags:["personalisering","kall e-post","svarsfrekvens"],body:"Personaliserad outreach är inte nytt. Det som är nytt är att göra det visuellt och i stor skala. När en prospekt öppnar ett mejl och ser sitt eget företagslogotyp placerat perfekt på din produktskärmbild händer något. Det signalerar ansträngning. Det signalerar relevans. Och det konverterar.\n\nStudier visar konsekvent att visuell personalisering slår textbaserade metoder. Svarsfrekvenser på 15 till 30% är uppnåeliga för team som implementerar logotypbaserad demopersonalisering, jämfört med branschsnittet på 2 till 5% för generisk kall e-post.\n\nKärnmekaniken är enkel: ladda upp din produktskärmbild en gång, hämta automatiskt prospektets logotyp och skicka en skräddarsydd bild som ser ut som om du lade en timme på den. Du lade 20 sekunder.\n\nDetta handlar inte om manipulation. Det handlar om att visa din prospekt att du förstår deras värld. En logotyp är den mest igenkännliga visuella tillgången ett företag har. När den visas i rätt kontext skapas omedelbar kontakt.\n\nSkala är den viktigaste fördelen. Att göra detta manuellt i Figma för en prospekt kan ta 30 minuter. Att göra det för 50 prospekter med Logoplacers tar 8 minuter totalt."},
  {slug:"kall-e-post-tips-sdr",lang:"sv",title:"Kall e-post i skala: En praktisk guide for SDR:er",excerpt:"De flesta SDR:er spenderar 70% av sin tid på manuell research. Har är hur du klipper ner det till under 5% utan att offra kvalitet.",cat:"Spelbok",rt:"7 min",date:"Mar 2025",tags:["SDR","kall e-post","automatisering"],body:"Den genomsnittliga SDR:en spenderar 3,5 timmar per dag pa research och personalisering. Det ar tid som inte laggs pa samtal, inte pa att stanga affarer. Och det mesta av den personaliseringen ar grundlaggande: fornamn, foretagsnamn, kanske en LinkedIn-detalj. Prospekter genomskådar det omedelbart.\n\nSkiftet till visuell personalisering andrar ekonomin. Istallet for att skriva en unik inledningsrad for varje prospekt skapar du en utmarkt visuell tillgang och later automatiseringen hantera personaliseringslagret.\n\nHar ar arbetsflödet: bygg din demoskärmbild i Logoplacers en gang. Lagg till textlager med platshallare som namn och foretag. Klistra sedan in din prospektlista och lat verktyget generera 50 unika personaliserade bilder pa under 2 minuter.\n\nVarje bild skickas direkt fran din Gmail med en 15 till 30 sekunders antispam-forsening mellan utskick. Prospekten tar emot ett mejl som ser ut som om du handgjorde en anpassad demo specifikt for dem.\n\nSDR:erna som anammar detta rapporterar 4 till 6 ganger hogre positiva svarsfrekvenser inom de forsta tva veckorna."},
  {slug:"hur-man-anvander-logoplacers",lang:"sv",title:"Hur man anvander Logoplacers: Komplett guide fran installation till forsta utskick",excerpt:"Steg-for-steg genomgang av Logoplacers — fran att ladda upp din forsta skärmbild till att skicka personaliserade demos till 50 prospekter.",cat:"Guide",rt:"8 min",date:"Feb 2025",tags:["guide","komma igang","tutorial"],body:"Den har guiden tar dig igenom hela Logoplacers-arbetsflödet fran din forsta inloggning till att skicka personaliserade demos till 50 prospekter.\n\nSteg 1 — Ladda upp din basbild\nDetta ar skärmbilden du vill personalisera. Idealt din produktgranssnitt eller en stark bild som representerar ditt vardeerbjiudande. Dra den till uppladdningszonen eller klicka for att bläddra. HEIC fran iPhone stods och konverteras automatiskt.\n\nSteg 2 — Positionera logotypplatshallaren\nLogotypplatshallaren visar var varje prospekts logotyp kommer att visas. Dra den till en naturlig position pa din bild — inuti en instrumentpanel, pa ett header, eller var som helst som ser avsiktligt ut snarare an inklistrat.\n\nSteg 3 — Lagg till textlager\nTextlager later dig lagga till personaliserad text som prospektets namn eller foretag. Anvand sidofältet for att lagga till lager och dra dem till position.\n\nSteg 4 — Lagg till prospekter\nKlistra in en lista over foretag i textomradet till hoger. Logoplacers gissar domänen och hämtar logotypen automatiskt.\n\nSteg 5 — Forhandsgranska\nKlicka pa Forhandsgranska for att se exakt hur varje personaliserad bild ser ut innan du skickar.\n\nSteg 6 — Skicka eller ladda ner\nAnslut Gmail med ett klick. Skriv din mejlmall med {name} och {company} platshallare. Tryck pa skicka."},
  {slug:"basta-saljverktyget-2025",lang:"sv",title:"Basta saljverktyget 2025: Vad som faktiskt fungerar",excerpt:"En praktisk guide till saljstacken som hogpresterande team anvander just nu, och vad som ar overhypat.",cat:"Bransch",rt:"6 min",date:"Mar 2025",tags:["saljverktyg","2025","stack"],body:"Den moderna saljstacken har exploderat. Det finns hundratals verktyg som lovar att 10x:a din pipeline. De flesta lever inte upp till loftet. Har ar vad som faktiskt gor skillnad.\n\nProspektering: Sales Navigator och Apollo ar standarden. Clay blir populart for databerikande i skala. Nyckelns ar listkvalitet over liststorlek.\n\nPersonalisering: Det har ar dar de flesta team underinvesterar. Generiska AI-skrivna mejl ar omedelbart identifierbara. Visuell personalisering — att bädda in prospektets varumärke i en demobild — är bade svarare att automatisera generiskt och mer effektivt.\n\nCRM: Salesforce for enterprise, HubSpot for tillvaxtfas, Pipedrive for enkelhet. Det basta CRM:et ar det ditt team faktiskt uppdaterar.\n\nDen en underutnyttjad taktiken 2025: visuell demopersonalisering. Team som lagger till en personaliserad skärmbild i den forsta kontakten ser konsekvent 2 till 4 ganger hogre positiva svar over alla andra verktyg i sin stack."},
  {slug:"skriva-ett-bra-saljmejl",lang:"sv",title:"Hur man skriver ett bra saljmejl som far svar 2025",excerpt:"Anatomin hos ett hogkonverterande kall mejl: amnesrad, oppning, vardeerbjudande, CTA. Med riktiga exempel.",cat:"Spelbok",rt:"7 min",date:"Mar 2025",tags:["saljmejl","copywriting","svarsfrekvens"],body:"De flesta kall mejl misslyckas av en av tre anledningar: de ar for langa, for generiska, eller de ber om for mycket for tidigt.\n\nHar ar anatomin hos ett kall mejl som konsekvent far svar.\n\nAmnesrad: 3 till 6 ord. Specifikt slar smart. 'Fraga om er salj process' slar 'Revolutionera er pipeline med AI'. Malet ar en nyfiken oppning, inte ett clickbait-lofte.\n\nOppningsrad: Borja aldrig med 'Jag'. Borja med dem. 'Sag att ni nyligen lanserade X' eller 'Ert team vaexer snabbt inom Y' visar research och fortjanar uppmärksamhet.\n\nVardeerbjudande: En mening. Vad gor du och varfor spelar det roll for den har specifika personen? Inte en funktionslista. Ett enda konkret resultat.\n\nVisuell krok: Inkludera en personaliserad demobild. En skärmbild med deras logotyp kommunicerar mer an tre stycken med text. Det ar det snabbaste sattet att gora det abstrakta konkret.\n\nUppmaning till handling: Be om nagot litet. 'Vart ett 15-minuters samtal?' eller 'Skulle detta vara anvandbart for ert team?' En ja/nej-fraga konverterar battre an 'Boka en demo pa min Calendly'.\n\nLangd: Under 100 ord for texten. Bilden gor det tunga lyftet."},
  {slug:"oka-svarsfrekvens-kall-outreach",lang:"sv",title:"Hur du far hogre svarsfrekvens pa kall outreach (Beprövade taktiker)",excerpt:"Varje taktik som har en matbar effekt pa kall e-post svarsfrekvenser, rankad fran hogst till lagst effekt.",cat:"Strategi",rt:"6 min",date:"Jan 2025",tags:["svarsfrekvens","outreach","taktiker"],body:"Att fa hogre svarsfrekvenser pa kall outreach handlar inte om att hitta en magisk fras. Det handlar om att stapla marginella vinster over varje element i din outreach.\n\nHogst effekt: Relevans. Att na ratt person vid ratt tidpunkt med ratt meddelande. Signalbaserad outreach — att rikta in sig pa manniskor som precis bytt jobb, tagit in kapital, eller lanserat en produkt — slar listbaserat spray-and-pray med 5 till 10 ganger.\n\nHog effekt: Visuell personalisering. Att bifoga en personaliserad demobild med prospektets logotyp okar svarsfrekvenserna mer an nagon textoptimering. Bilden kommunicerar relevans snabbare an ord.\n\nMedeleffekt: Amnesrad. Under 50 tecken. Specifikt och nyfiket slar smart och hypigt. Testa flera versioner.\n\nMedeleffekt: Skicktid. Tisdag till torsdag morgon i prospektets tidszon. Undvik mandagsmorgon och fredagseftermiddag.\n\nLagre effekt men fortfarande meningsfull: Uppfoljningssekvens. En uppfoljning lagger till 20 till 30% fler svar. Mer an tre uppfoljningar visar avtagande avkastning."},
];

const CAT_COLORS = {Strategy:"#1a82ff",Playbook:"#8b5cf6",Tutorial:"#10b981",Industry:"#f59e0b",Comparison:"#ec4899",Product:"#06b6d4",Strategi:"#1a82ff",Spelbok:"#8b5cf6",Guide:"#10b981",Bransch:"#f59e0b"};

function BlogCard({ p, onClick }) {
  const [hov, setHov] = useState(false);
  const c = CAT_COLORS[p.cat] || "#1a82ff";
  const t = useT();
  return (
    <article onMouseEnter={()=>setHov(true)} onMouseLeave={()=>setHov(false)} onClick={()=>onClick(p)}
      itemScope itemType="https://schema.org/BlogPosting"
      style={{background:hov?"rgba(255,255,255,.045)":"rgba(255,255,255,.018)",border:`1px solid ${hov?`${c}44`:"rgba(255,255,255,.06)"}`,borderRadius:20,padding:"26px 24px",cursor:"pointer",transition:"border-color .2s,background .2s,box-shadow .2s,transform .2s",boxShadow:hov?`0 14px 44px rgba(0,0,0,.3),0 0 0 0.5px ${c}18`:"none",transform:hov?"translateY(-2px)":"translateY(0)",display:"flex",flexDirection:"column",gap:13}}>
      <meta itemProp="headline" content={p.title}/>
      <meta itemProp="datePublished" content={p.date}/>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:8}}>
        <div style={{display:"flex",gap:6,alignItems:"center"}}>
          <span style={{fontSize:10,fontWeight:700,letterSpacing:"1.5px",textTransform:"uppercase",color:c,background:`${c}14`,border:`1px solid ${c}30`,borderRadius:6,padding:"3px 8px"}}>{p.cat}</span>
          {p.lang==="sv" && <span style={{fontSize:10,fontWeight:700,letterSpacing:"1px",color:"rgba(255,255,255,.3)",background:"rgba(255,255,255,.05)",border:"1px solid rgba(255,255,255,.08)",borderRadius:6,padding:"3px 7px"}}>SV</span>}
        </div>
        <span style={{fontSize:11,color:"rgba(255,255,255,.24)"}}>{p.rt} read</span>
      </div>
      <h2 itemProp="name" style={{fontSize:15,fontWeight:700,color:"#fff",margin:0,letterSpacing:"-.3px",lineHeight:1.34}}>{p.title}</h2>
      <p itemProp="description" style={{fontSize:12,color:"rgba(255,255,255,.4)",lineHeight:1.65,margin:0,flex:1}}>{p.excerpt}</p>
      <div style={{display:"flex",alignItems:"center",justifyContent:"space-between"}}>
        <span style={{fontSize:11,color:"rgba(255,255,255,.24)"}}>{p.date}</span>
        <span style={{fontSize:12,color:c,fontWeight:600}}>{t("blog.read_more")} →</span>
      </div>
    </article>
  );
}

function BlogPost({ p, onBack }) {
  const c = CAT_COLORS[p.cat] || "#1a82ff";
  const t = useT();
  useEffect(() => {
    window.scrollTo(0,0);
    document.title = `${p.title} — Logoplacers Blog`;
    return () => { document.title = "Logoplacers"; };
  }, [p]);
  return (
    <div style={{maxWidth:720,margin:"0 auto",padding:"40px 24px 80px"}}>
      <button onClick={onBack} style={{display:"flex",alignItems:"center",gap:8,background:"none",border:"none",color:"rgba(255,255,255,.4)",fontSize:13,cursor:"pointer",fontFamily:"inherit",padding:0,marginBottom:40,transition:"color .15s"}}
        onMouseEnter={e=>e.currentTarget.style.color="#fff"} onMouseLeave={e=>e.currentTarget.style.color="rgba(255,255,255,.4)"}>
        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><polyline points="15 18 9 12 15 6"/></svg>
        {t("blog.all_posts")}
      </button>
      <span style={{fontSize:10,fontWeight:700,letterSpacing:"1.5px",textTransform:"uppercase",color:c,background:`${c}14`,border:`1px solid ${c}30`,borderRadius:6,padding:"4px 10px",display:"inline-block",marginBottom:20}}>{p.cat}</span>
      <h1 style={{fontSize:"clamp(24px,4vw,40px)",fontWeight:800,letterSpacing:"-1.5px",margin:"0 0 16px",lineHeight:1.15,color:"#fff"}}>{p.title}</h1>
      <div style={{display:"flex",gap:14,marginBottom:48,fontSize:12,color:"rgba(255,255,255,.28)"}}>
        <span>{p.date}</span><span>·</span><span>{p.rt} read</span>
        {p.lang==="sv" && <span style={{background:"rgba(255,255,255,.06)",padding:"1px 7px",borderRadius:5}}>Svenska</span>}
      </div>
      <div style={{fontSize:16,color:"rgba(255,255,255,.65)",lineHeight:1.85}}>
        {p.body.trim().split("\n\n").map((para,i)=>{
          const isHeader = /^(Step \d|Template \d|Steg \d|[A-Z][A-Z ]{6,}:)/.test(para.trim());
          const isBullet = para.trim().startsWith("—") || para.trim().startsWith("-");
          if (isHeader) return (
            <h2 key={i} style={{fontSize:18,fontWeight:800,color:"#fff",letterSpacing:"-.5px",margin:"36px 0 10px",lineHeight:1.3}}>{para}</h2>
          );
          if (isBullet) return (
            <div key={i} style={{display:"flex",gap:10,margin:"0 0 14px",paddingLeft:4}}>
              <span style={{color:c,flexShrink:0,marginTop:3}}>→</span>
              <p style={{margin:0}}>{para.replace(/^[—\-]\s*/,"")}</p>
            </div>
          );
          return <p key={i} style={{margin:"0 0 22px"}}>{para}</p>;
        })}
      </div>
      <div style={{display:"flex",flexWrap:"wrap",gap:7,marginTop:40,paddingTop:32,borderTop:"1px solid rgba(255,255,255,.06)"}}>
        {p.tags.map(tag=><span key={tag} style={{fontSize:11,color:"rgba(255,255,255,.32)",background:"rgba(255,255,255,.04)",border:"1px solid rgba(255,255,255,.08)",borderRadius:6,padding:"3px 9px"}}>#{tag}</span>)}
      </div>
      <div style={{marginTop:56,background:"rgba(26,130,255,.07)",border:"1px solid rgba(26,130,255,.2)",borderRadius:20,padding:"32px 28px",textAlign:"center"}}>
        <p style={{fontSize:14,color:"rgba(255,255,255,.5)",margin:"0 0 8px"}}>{t("blog.cta_sub")}</p>
        <h3 style={{fontSize:20,fontWeight:800,letterSpacing:"-1px",margin:"0 0 20px",color:"#fff"}}>{t("blog.cta_title")}</h3>
        <a href="#app" style={{display:"inline-block",background:"linear-gradient(135deg,#1a82ff,#5b4fff)",color:"#fff",textDecoration:"none",borderRadius:12,padding:"12px 28px",fontSize:14,fontWeight:700,boxShadow:"0 8px 24px rgba(26,130,255,.35)"}}>
          {t("blog.cta_btn")} →
        </a>
      </div>
    </div>
  );
}

function BlogIndex({ onPost }) {
  const [filter, setFilter] = useState("All");
  const { lang, setLang } = useLang();
  const t = useT();
  const cats = lang==="en"
    ? ["All","Strategy","Playbook","Tutorial","Industry","Comparison","Product"]
    : ["All","Strategi","Spelbok","Guide","Bransch"];
  const shown = POSTS.filter(p=>p.lang===lang).filter(p=>filter==="All"||p.cat===filter);
  return (
    <div style={{maxWidth:1100,margin:"0 auto",padding:"60px 24px 80px"}}>
      <div style={{textAlign:"center",marginBottom:56}}>
        <div style={{fontSize:11,fontWeight:700,letterSpacing:"2px",color:"#1a82ff",textTransform:"uppercase",marginBottom:14}}>Blog</div>
        <h1 style={{fontSize:"clamp(32px,5vw,56px)",fontWeight:800,letterSpacing:"-2.5px",margin:"0 0 14px",lineHeight:1.04}}>
          {t("blog.title")}
        </h1>
        <p style={{fontSize:16,color:"rgba(255,255,255,.36)",maxWidth:420,margin:"0 auto 28px"}}>
          {t("blog.sub")}
        </p>
        {/* Language toggle */}
        <div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:20}}>
          {[{code:"en",label:t("blog.lang_en")},{code:"sv",label:t("blog.lang_sv")}].map(l=>(
            <button key={l.code} onClick={()=>{setLang(l.code);setFilter("All");}} style={{background:lang===l.code?"rgba(26,130,255,.15)":"rgba(255,255,255,.04)",border:`1px solid ${lang===l.code?"rgba(26,130,255,.38)":"rgba(255,255,255,.08)"}`,color:lang===l.code?"#60a5fa":"rgba(255,255,255,.42)",borderRadius:100,padding:"5px 16px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit",transition:"all .15s"}}>{l.label}</button>
          ))}
        </div>
        <div style={{display:"flex",flexWrap:"wrap",gap:7,justifyContent:"center"}}>
          {cats.map(cat=>(
            <button key={cat} onClick={()=>setFilter(cat)} style={{background:filter===cat?"rgba(26,130,255,.15)":"rgba(255,255,255,.04)",border:`1px solid ${filter===cat?"rgba(26,130,255,.38)":"rgba(255,255,255,.08)"}`,color:filter===cat?"#60a5fa":"rgba(255,255,255,.42)",borderRadius:100,padding:"6px 16px",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:"inherit",transition:"all .15s"}}>{cat}</button>
          ))}
        </div>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:16}}>
        {shown.map(p=><BlogCard key={p.slug} p={p} onClick={onPost}/>)}
      </div>
    </div>
  );
}

export default function Blog() {
  const [activePost, setActivePost] = useState(null);
  useEffect(() => {
    const hash = window.location.hash.replace("#","");
    if (hash) { const found = POSTS.find(p=>p.slug===hash); if (found) setActivePost(found); }
  }, []);
  const handlePost = (p) => { setActivePost(p); window.location.hash = p.slug; window.scrollTo(0,0); };
  const handleBack = () => { setActivePost(null); window.location.hash = ""; window.scrollTo(0,0); };
  return (
    <div style={{background:"#070b12",color:"#fff",minHeight:"100vh",fontFamily:"'DM Sans','Helvetica Neue',sans-serif"}}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"/>
      <nav style={{position:"sticky",top:0,zIndex:100,height:60,padding:"0 32px",display:"flex",alignItems:"center",justifyContent:"space-between",background:"rgba(7,11,18,.92)",backdropFilter:"blur(20px)",WebkitBackdropFilter:"blur(20px)",borderBottom:"1px solid rgba(255,255,255,.06)"}}>
        <a href="#" onClick={e=>{e.preventDefault();window.location.hash="";}} style={{display:"flex",alignItems:"center",gap:9,textDecoration:"none"}}>
          <Logo size={28}/>
          <span style={{fontSize:15,fontWeight:700,color:"#fff",letterSpacing:"-.3px"}}>Logoplacers</span>
          <span style={{fontSize:12,color:"rgba(255,255,255,.25)",margin:"0 2px"}}>/</span>
          <span style={{fontSize:13,color:"rgba(255,255,255,.45)",fontWeight:500}}>Blog</span>
        </a>
        <a href="#app" style={{background:"linear-gradient(135deg,#1a82ff,#5b4fff)",color:"#fff",textDecoration:"none",borderRadius:10,padding:"8px 18px",fontSize:13,fontWeight:700,boxShadow:"0 4px 16px rgba(26,130,255,.3)"}}>
          Try free →
        </a>
      </nav>
      {activePost ? <BlogPost p={activePost} onBack={handleBack}/> : <BlogIndex onPost={handlePost}/>}
      <footer style={{borderTop:"1px solid rgba(255,255,255,.05)",padding:"24px 32px",display:"flex",alignItems:"center",justifyContent:"space-between",flexWrap:"wrap",gap:12}}>
        <div style={{display:"flex",alignItems:"center",gap:8}}><Logo size={22}/><span style={{fontSize:13,fontWeight:600,color:"rgba(255,255,255,.4)"}}>Logoplacers</span></div>
        <span style={{fontSize:12,color:"rgba(255,255,255,.2)"}}>Personalised sales demos that convert.</span>
        <a href="#" onClick={e=>{e.preventDefault();window.location.hash="";}} style={{fontSize:12,color:"rgba(255,255,255,.3)",textDecoration:"none"}}>Back to home</a>
      </footer>
      <style>{`*{box-sizing:border-box}html{scroll-behavior:smooth}`}</style>
    </div>
  );
}
